<a href="https://colab.research.google.com/github/codingjobrice/Machine-Learning/blob/main/1_3_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# NumPy(numerical python) : 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지

import numpy as np

# 1차원 배열
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

# 2차원 배열
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])     # 1행 3열인 2차원 배열. 차이점은 [[]]
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1: 1차원, array2: 2차원, array3:  2차원


In [ ]:
# ndarray의 데이터 타입
# ndarray내의 데이터 타입은 같은 데이터 타입만 가능

list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

# 다른 데이터 유형이 섞여 있는 리스트를 ndarray 변환 시 더 큰 데이터 타입으로 형 변환
list2=[1,2,'test']    # 문자열의 데이터 타입이 더 크므로 1은 '1'로 형 변환
array2=np.array(list2)
print(array2,array2.dtype)

list3=[1,2,3.0]    # 마찬가지로 실수형이 더 크므로 1이 1.0으로 변한다.
array3=np.array(list3)
print(array3,array3.dtype)

# list3 같은 경우 1,2 를 실수형으로 변환하는 것은 낭비임
# 고로 3.0을 정수 타입으로 변환하는 것이 메모리 절약에 도움됨
# astype을 활용

array_int = np.array([1,2,3])
array_float = array_int.astype('float64')    # int를 float로
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')    # float를 int로
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])    # float를 int로
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' 'test'] <U21
[1. 2. 3.] float64
[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [ ]:
# ndarray 편리하게 생성하기
# arange, zeros, ones 활용

# arange
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

# zeros, ones
zero_array=np.zeros((3,2),dtype='int32')    # 데이터 타입 미설정 시 float형으로 초기화
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))    # 그래서 얘는 데이터 타입이 float형 ㅇㅋ?
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [ ]:
# reshape()
# ndarray를 특정 차원 및 크기로 변환

array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)    # 2행 5열
print('array2:\n',array2)

array3=array1.reshape(5,2)    # 5행 2열
print('array3:\n',array3)

# 인자를 -1로 사용하는 경우
array4=array1.reshape(-1,5)    # 자동으로 조정해준다. 10개의 데이터가 있고 5개의 열을 설정하면 -1을 사용했을 때 행을 2로 설정해줌
print('array4:\n',array4)

array5=array1.reshape(5,-1)    # 마찬가지로 행이 5니까 열을 2로 설정. 참고로 low는 열 column은 행
print('array5:\n',array5)

# array6=array1.reshape(4,-1) -> 오류
# 주로 reshape(-1,1)로 자주 사용된다.

array6=np.arange(8)
array3d=array6.reshape((2,2,2))
print('array3d:\n',array3d.tolist())    # tolist: 리스트로 변환

# 3차원 ndarray를 2차원으로 변환
array7=array3d.reshape(-1,1)
print('array7:\n', array7.tolist())
print('array7 shape:', array7.shape)

# 1차원을 2차원으로 변환
array8=array6.reshape(-1,1)
print('array8:\n', array8.tolist())
print('array8 shape:', array8.shape)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array4:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array5:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array7:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array7 shape: (8, 1)
array8:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array8 shape: (8, 1)


In [ ]:
# 인덱싱 : ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록 함
# 1. 특정한 데이터만 추출
# 2. 슬라이싱
# 3. 팬시 인덱싱
# 4. 불린 인덱싱

# 1. 특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환
# 단일 값 추출
# 1차원

array1 = np.arange(start=1,stop=10)
print('array1:',array1)
value=array1[2]
print('value:',value)
print(type(value))
print('맨 뒤의 값:',array1[-1],' 맨 뒤에서 두 번째 값:',array1[-2])    # 배열에서 -1은 맨 마지막, -2는 마지막 앞을 의미
array1[0] = 9
array1[8] = 0
print('array1:',array1)    # 값 변경 가능

# 2차원
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:',array2d[0,0])
print('(row=0, col=1) index 가리키는 값:',array2d[0,1])
print('(row=1, col=0) index 가리키는 값:',array2d[1,0])
print('(row=2, col=2) index 가리키는 값:',array2d[2,2])



array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9  맨 뒤에서 두 번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [ ]:
# 슬라이싱
array1 = np.arange(start=1,stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

# ':' 기호 앞에 시작 인덱스를 생략하면 0부터라고 간주
array4=array1[:3]
print(array4)

# ':' 기호 뒤에 종료 인덱스를 생략하면 끝까지라고 간주
array5=array1[3:]
print(array5)

# ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 처음/마지막 인덱스로 간주
array6=array1[:]
print(array6)

# 2차원
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print("array2d:\n",array2d)

print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:,:]\n',array2d[:,:])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2,0]\n',array2d[:2,0])

# 2차원에서 array2d[0] 처럼 한 행을 가져오면 그 행렬은 1차원이 된다.
print(array2d[0])
print('array2d[0] shape: ',array2d[0].shape)
      



[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]
[1 2 3]
array2d[0] shape:  (3,)


In [ ]:
# 팬시 인덱싱 (fancy indexing)
# 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2] => ',array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ',array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


In [ ]:
# 불린 인덱싱 (boolean indexing)
# 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식

array1d=np.arange(start=1, stop=10)
# [] 안에 array1d>5 boolean indexing 적용
array3=array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값:',array3)

print(array1d>5)
# 보시다시피 [False False False False False  True  True  True  True] 로 출력되며 5보다 큰 값은 True, 5 이하는 False가 출력된다.
# False 인덱스는 무시하고 True 인덱스만 출력하여 [6 7 8 9] 가 출력됨

boolean_indexes=np.array([False,False,False,False,False,True,True,True,True])
array4=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 : ',array4)


array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]
[False False False False False  True  True  True  True]
불린 인덱스로 필터링 결과 :  [6 7 8 9]


In [ ]:
# 행렬의 정렬
# sort() 와 argsort()

org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)

# np.sort()로 정렬
# 원 행렬은 유지한 채 원 행렬의 정렬된 행렬을 반환
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)

# ndarray.sort()로 정렬
# 원 행렬 자체를 정렬한 형태로 반환하며 반환 값은 None
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:',org_array)

# 한마디로 원본은 냅두고 정렬된 행렬을 가지고 싶으면 'np.sort()'
# 원본 행렬 자체를 정렬하고 싶으면 '행렬.sort()'

# 둘 다 기본적으로 오름차순으로 정렬
# 내림차순으로 정렬하기
sort_array1_desc=np.sort(org_array)[::-1]
print("내림차순으로 정렬:",sort_array1_desc)

# low 방향, column 방향으로 정렬하기
array2d=np.array([[8,12],
                  [7,1]])
# low 방향으로
sort_array2d_axis0=np.sort(array2d,axis=0)
print("로우 방향으로 정렬:\n",sort_array2d_axis0)
# column 방향으로
sort_array2d_axis1=np.sort(array2d,axis=1)
print("칼럼 방향으로 정렬:\n",sort_array2d_axis1)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]
로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [ ]:
# argsort()
# 원본 행렬이 정렬되었을 때 기존 원본 행렬의 인덱스를 필요로 할 때 사용

org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

# 마찬가지로 내림차순으로 할 때는 [::-1]을 사용한다
org_array2=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

# 활용

name_array=np.array(["John","Mike","Sarah","Kate","Samuel"])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print("성적 오름차순 정렬 시 score_array의 인덱스:",sort_indices_asc)
print("성적 오름차순으로 name_array의 이름 출력:",name_array[sort_indices_asc])


<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]
성적 오름차순 정렬 시 score_Array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [ ]:
# 행렬 연산

# 내적
# 곱해서 더하는 것이다. 알아서 찾아봐라
A=np.array([[1,2,3],
           [4,5,6]])
B=np.array([[7,8],
           [9,10],
           [11,12]])
dot_product=np.dot(A,B)
print("행렬 내적 결과: \n",dot_product)

# 전치 행렬
# 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬을 그 행렬의 전치 행렬이라고 한다.

transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

행렬 내적 결과: 
 [[ 58  64]
 [139 154]]
A의 전치 행렬:
 [[1 4]
 [2 5]
 [3 6]]
